import { Html, Head, Main, NextScript } from 'next/document'
// import Home from '.'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <body>
        {/* <h1>Lols</h1> */}
        <Main />
        <NextScript />
        <footer>

        </footer>
      </body>  
    </Html>
    // <Home></Home>
  )
}
